name: Work Hours Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
    DATABASE_URL: postgresql://postgres:root@localhost:5432/work_hours_db
    SECRET_KEY: cd586e9df23daec541e4b803e1b78041
    CREATE_USER_APY: 1e4e2224430117b4c8ccc461b5237843

jobs:   
  build:
    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:14.5
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
          ports:
            - 5432:5432
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Create Prisma Database
        run: npx prisma migrate dev

      - name: Construir e iniciar servidor web local
        run: npm run start &

      - name: Clone Cypress repository
        run: git clone https://github.com/AllanScala1991/work-hours-api-tests

      - name: Install Cypress dependencies
        run: cd work-hours-api-tests && npm i

      - name: Run Cypress tests
        run: cd work-hours-api-tests && npm run cy:test